import React, { useState, useEffect } from 'react';
import { Product } from '../services/productService'; // Assuming Product interface

// Extend the Product type for the form submission to include a File object
// Omit fields that are generated by the backend
interface ProductFormData {
  name: string;
  description: string;
  price: number;
  category: string;
  brand: string;
  stock: number;
  imageUrl: string; // This will be the URL if no file is uploaded, or the old URL during edit
  imageFile?: File | null; // Optional: for file upload
}

interface ProductFormProps {
  initialData?: Product; // Optional: for editing existing products
  onSubmit: (productData: ProductFormData) => Promise<void>;
  loading: boolean;
  error: string | null;
}

function ProductForm({ initialData, onSubmit, loading, error }: ProductFormProps) {
  const [name, setName] = useState(initialData?.name || '');
  const [description, setDescription] = useState(initialData?.description || '');
  const [price, setPrice] = useState(initialData?.price || 0);
  const [category, setCategory] = useState(initialData?.category || '');
  const [brand, setBrand] = useState(initialData?.brand || '');
  const [stock, setStock] = useState(initialData?.stock || 0);
  const [imageUrl, setImageUrl] = useState(initialData?.imageUrl || '');
  const [imageFile, setImageFile] = useState<File | null>(null); // For new file upload
  const [imagePreview, setImagePreview] = useState<string | null>(null); // For local image preview

  useEffect(() => {
    if (initialData) {
      setName(initialData.name);
      setDescription(initialData.description);
      setPrice(initialData.price);
      setCategory(initialData.category);
      setBrand(initialData.brand);
      setStock(initialData.stock);
      setImageUrl(initialData.imageUrl);
      setImagePreview(initialData.imageUrl); // Show existing image
    } else {
      // Clear form and preview on new product
      setName('');
      setDescription('');
      setPrice(0);
      setCategory('');
      setBrand('');
      setStock(0);
      setImageUrl('');
      setImageFile(null);
      setImagePreview(null);
    }
  }, [initialData]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setImageFile(file);
      // Create a local URL for image preview
      setImagePreview(URL.createObjectURL(file));
      setImageUrl(''); // Clear URL input if a file is selected
    } else {
      setImageFile(null);
      setImagePreview(initialData?.imageUrl || null); // Revert to existing URL or null
    }
  };

  const handleImageUrlChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setImageUrl(e.target.value);
    setImageFile(null); // Clear file if URL is being used
    setImagePreview(e.target.value); // Show preview from URL
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onSubmit({ name, description, price, category, brand, stock, imageUrl, imageFile });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label htmlFor="name" className="block text-gray-700 text-sm font-bold mb-2">Product Name:</label>
        <input
          type="text"
          id="name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          required
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        />
      </div>
      <div>
        <label htmlFor="description" className="block text-gray-700 text-sm font-bold mb-2">Description:</label>
        <textarea
          id="description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          required
          rows={4}
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        ></textarea>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label htmlFor="price" className="block text-gray-700 text-sm font-bold mb-2">Price:</label>
          <input
            type="number"
            id="price"
            value={price}
            onChange={(e) => setPrice(parseFloat(e.target.value))}
            min="0"
            step="0.01"
            required
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          />
        </div>
        <div>
          <label htmlFor="category" className="block text-gray-700 text-sm font-bold mb-2">Category:</label>
          <input
            type="text"
            id="category"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            required
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          />
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label htmlFor="brand" className="block text-gray-700 text-sm font-bold mb-2">Brand:</label>
          <input
            type="text"
            id="brand"
            value={brand}
            onChange={(e) => setBrand(e.target.value)}
            required
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          />
        </div>
        <div>
          <label htmlFor="stock" className="block text-gray-700 text-sm font-bold mb-2">Stock:</label>
          <input
            type="number"
            id="stock"
            value={stock}
            onChange={(e) => setStock(parseInt(e.target.value))}
            min="0"
            required
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          />
        </div>
      </div>
      <div>
        <label htmlFor="imageUrl" className="block text-gray-700 text-sm font-bold mb-2">Upload Image :</label>
        <input
          type="file"
          id="imageFile"
          accept="image/*"
          onChange={handleFileChange}
          className="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
        />
        <p className="text-sm text-gray-500 mt-1">OR provide an Image URL:</p>
        <input
          type="url"
          id="imageUrl"
          value={imageUrl}
          onChange={handleImageUrlChange}
          disabled={!!imageFile} // Disable if a file is selected
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mt-2 disabled:bg-gray-200 disabled:cursor-not-allowed"
          placeholder="e.g., http://example.com/image.jpg"
        />
        {imagePreview && (
          <div className="mt-4">
            <p className="text-gray-700 text-sm font-bold mb-2">Image Preview:</p>
            <img src={imagePreview} alt="Product Preview" className="h-48 w-48 object-cover rounded-lg shadow-md" />
          </div>
        )}
        {imageUrl && <img src={imageUrl} alt="Product Preview" className="mt-2 h-24 w-24 object-cover rounded" />}
        {!imageFile && !imageUrl && !initialData?.imageUrl && (
          <p className="text-red-500 text-sm mt-2">Image or Image URL is required.</p>
        )}
      </div>

      {error && <p className="text-red-600 text-sm text-center">{error}</p>}
      <button
        type="submit"
        disabled={loading}
        className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full disabled:opacity-50"
      >
        {loading ? 'Saving...' : (initialData ? 'Update Product' : 'Create Product')}
      </button>
    </form>
  );
}

export default ProductForm;